### ISSUE TITLE
Error exporting cohort into BQ table

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#492] opened 2020-12-14 20:40 UTC
Reproducible with a cohort created with the previous release, in production tier, after "clear cache and hard reboot".

![image](https://user-images.githubusercontent.com/313942/102133080-8d938e80-3e22-11eb-87ca-84799ae064c5.png)

**Comment by fedorov** [comment] 2020-12-14 20:43
I can reproduce this error with cohorts ID 38 and 34 under my account, but cohort ID 33 works.

**Comment by madelyngreyes** [comment] 2020-12-14 22:10
I also returned an error for the cohorts below, 

![cohort administrator error](https://user-images.githubusercontent.com/16824894/102141669-36e08180-3e2f-11eb-96e1-ac72d9a99727.PNG)

![please contact admin BigQuery export](https://user-images.githubusercontent.com/16824894/102141675-3942db80-3e2f-11eb-9e48-e5a2b319c3ce.PNG)

**Comment by s-paquette** [comment] 2020-12-16 23:22
Problem is in the BQ query builder; it's treating some numeric fields as strings. I'll see how easy it is to find the problem but we may want to just patch it via a forced schema. We'll see.

**Comment by s-paquette** [comment] 2020-12-17 00:29
Okay, the issue is with multiple ranges of numerics. Which is to say (a between 1 and 2 OR a between 3 and 4). Just about have a fix done.

**Comment by s-paquette** [comment] 2021-01-15 01:58
I think this got stealth fixed in Sprint 16. Going to mark it for testing @madelyngreyes @fedorov when you have a chance,

**Closed** 2021-01-18 16:19 UTC
Labels: bug, cohorts, merged:dev, production, testing needed, testing passed
