### ISSUE TITLE
`tcia_tumorLocation` is misleading and should not be used in the URL filter

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1340] opened 2023-12-11 17:48 UTC
IDC curates data from multiple sources other than TCIA. It is misleading to refer to this deprecated attribute. `TCIA Tumor Location" is unknown (and indicating this otherwise in our metadata is incorrect and misleading) for datasets that are coming to IDC from sources other than TCIA. TCIA knows nothing about those datasets.

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/34bd374a-a3a1-41a2-ad68-6dbd63344cfe)

**Comment by bcli4d** [comment] 2023-12-11 18:02
@s-paquette, dicom_all has a collection_tumorLocation column. The tcia_tumorLocation column is described as deprecated. 
Similarly collection_cancerType/tcia_cancerType and collection_species/tcia_species.

**Comment by s-paquette** [comment] 2023-12-11 18:26
Duplicate of #1256

**Closed by s-paquette** 2023-12-11 18:26 UTC
Labels: wontfix
