### ISSUE TITLE
400 error if many filters selected will cause an error on the exploration page

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#622] opened 2021-05-13 19:26 UTC
Selection of all filters from the collections, body part examined, and the modality filter options will cause an infinite loading wheel to appear, and a 400 error within the dev console. 

<img width="1333" alt="Screen Shot 2021-05-13 at 3 19 44 PM" src="https://user-images.githubusercontent.com/16824894/118176519-82f41a00-b3ff-11eb-9f82-fb8d0279ab54.png">

**Comment by s-paquette** [comment] 2021-05-24 03:14
Note this is the same issue as #624 so I closed that as a duplicate.

We need to decide if we want to either limit the length of selected filters, or, change the data type in MySQL. In CGC we have a limit on how many filter values (which is the actual issue) a user can choose. @fedorov @ulrikew do we have a preference here?

**Comment by fedorov** [comment] 2021-05-24 16:29
What are the likely or possible consequences of changing the data type in MySQL?

**Comment by s-paquette** [comment] 2021-05-24 16:52
The main issue is size of the MySQL database long-term, and maintenance of it in a general sense. The more data users are storing, the bigger it gets, the more it will cost us. And even the text format has a limit of 65k characters, so as we obtain more collections that too will eventually be insufficient. 

So although we can shift to text for now, we still need to consider a max long term.

**Comment by G-White-ISB** [comment] 2021-05-24 17:56
As implemented the DB stores a string listing all values (by name) selected for each attribute in the filter.  So 2 values with long names may require more space than 3 with short names. Current limit is 256 characters. Current worse case scenario (a string with all collection names) seems to be about 1700 characters.

**Comment by s-paquette** [comment] 2021-05-24 18:02
So this would buy us some time, but ultimately, we're going to hit a limit, and it'd be best if we decided what that is right now.

**Comment by madelyngreyes** [comment] 2021-06-07 12:37
On the exploration page, filters from all tabs where selected to create a large cohort was successful. 

![Screen Shot 2021-06-07 at 8 36 50 AM](https://user-images.githubusercontent.com/16824894/121017734-9b8bf180-c76b-11eb-9400-e40ce42c4514.png)

**Comment by fedorov** [comment] 2021-06-08 15:24
@s-paquette @G-White-ISB before I close this issue - what is the expected behavior when hitting the limit? will user be alerted, or it will only show up in the console?

**Comment by fedorov** [comment] 2021-06-08 15:26
Also, with a long cohort definition, when cohort is selected, it is opened with empty filter, and after some time progress spinner shows up. Is this the expected behavior?

**Comment by G-White-ISB** [comment] 2021-06-08 15:35
The DB has been retooled so that for now no possible set of filters should exceed the limit. 

When selecting a cohort the browser loads the page, then there is an automatic request sent to fetch the cohort data. This will cause the spinner to 'show up'. However the spinner should only stay for a few seconds after which the cohort should be loaded, and it's filters should appear in the filter definition.

**Closed** 2021-06-08 16:07 UTC
Labels: In Progress, bug, explore page, merged:dev, testing needed, testing passed
