### ISSUE TITLE
Toolbar icons should line up with the logged user icon on the right

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#268] opened 2020-09-10 13:38 UTC
Right now they are not

![image](https://user-images.githubusercontent.com/313942/92737683-5906c700-f349-11ea-8155-428e2585a8d8.png)

**Comment by mitianisb** [comment] 2020-09-13 06:31
![image](https://user-images.githubusercontent.com/58752821/93011910-e7e53080-f54f-11ea-9a77-734c9905ddc6.png)
I have fixed the top alignment. The bottom is not aligned because the user icon is 40x40, and the toobar icons is 32x32. I tried 32x32 for the user icon but it looks too small.

**Comment by madelyngreyes** [comment] 2020-09-14 20:37
At 110% zoom the toolbar icons appear above the user icon. 
<img width="960" alt="2020-09-14 (24)" src="https://user-images.githubusercontent.com/16824894/93135477-65bc4f80-f6a8-11ea-991c-a5dca1b1b11f.png">


Then at 125% zoom the toolbar icons appear to be aligned with the user icon.
<img width="960" alt="2020-09-14 (25)" src="https://user-images.githubusercontent.com/16824894/93135487-694fd680-f6a8-11ea-899b-1aab0ac15cb4.png">

**Comment by s-paquette** [comment] 2020-09-15 05:39
@madelyngreyes The bug isn't in reference to what you have in the screenshots. That overflow is a natural result of the toolbar not having enough room. Andrey's original comment is that when the navigation icons and the login are on the same line, they're not lined up. The staggering due to lack of screen size is as-expected.

**Comment by madelyngreyes** [comment] 2020-09-15 19:15
Okay, I will close this ticket then. Is there an open ticket for the screen size issue or just leave it as is for now? @s-paquette

**Comment by s-paquette** [comment] 2020-09-15 19:24
There isn't because that flow of the icons is working as intended.

**Closed** 2020-09-16 21:44 UTC
Labels: MVP, enhancement, merged, testing needed, testing passed
