### ISSUE TITLE
Test Tier - Blank slide for Positron Emission Tomography (PET)

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1130] opened 2023-01-27 18:49 UTC
Test Link - https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.5168.1900.259520120774497994844579066293

**Steps to reproduce:**

1. Open IDC home page
2. Click carousel Positron Emission Tomography (PET) image
3. Click 3 rd slide on the left. It is blank.

![image](https://user-images.githubusercontent.com/106698935/215169842-35dc0203-831d-4ff0-8638-788c8ffccb9a.png)
![image](https://user-images.githubusercontent.com/106698935/215169947-3a793fc3-dec3-4dfc-abef-7f88fe0a2d47.png)

**Comment by s-paquette** [comment] 2023-02-16 20:36
This is a duplicate of #1140 which Andrey has indicated how to fix.

**Closed** 2023-02-16 20:36 UTC
Labels: duplicate
