### ISSUE TITLE
Display last-exported table on cohort list page

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#554] opened 2021-02-19 20:44 UTC
After exporting a manifest to Big Query, you click on the link and it replaces the page, as opposed to opening in another tab. I do various copy operations to my project, and then I have to back up a few tabs to get back to the WebApp. I overshot, and when I got back to the portal, I no longer had the info on where the table lived. It would be useful to 1) Open BQ in new tab, 2) Record the table location for the manifest along with the cohort, so I can get back to it in the future. Thoughts?

**Comment by pieper** [comment] 2021-02-19 21:24
I agree, I was going to suggest the new tab for BQ too.

**Comment by madelyngreyes** [comment] 2021-02-19 21:55
We currently have this ticket open to address opening the link in a new tab. https://github.com/ImagingDataCommons/IDC-WebApp/issues/517 

To address your second point it's my understanding this will be difficult to do. But, Suzanne would have more information. @s-paquette

**Comment by s-paquette** [comment] 2021-02-19 22:33
The later is an issue in terms of timeout; the table will be deleted after a week, but possibly still exists in the cohort table. We'll need to implement a cron job to delete the entry once the table expires. So, doable, needs some significant work.

**Comment by s-paquette** [comment] 2021-03-08 23:46
Just adding a note that this would be a significant addition, and include a cron task or similar to time out the entries on the display page, so we'd need to decide how important we think it is.

**Comment by s-paquette** [comment] 2022-03-16 21:20
Simpler/alternative methodology: 

- Add 'last exported table' link as a cohort field, and 'last exported date'
- On cohort details or list page load, check all non-NULL dates and if any are greater than the expiration time (7 days), mark them as stale
- Otherwise, provide a link to the table

This will only show the most recent export, rather than a history of them. Is that still okay, @wlongabaugh @pieper @fedorov ?

**Comment by fedorov** [comment] 2022-03-16 22:58
Isn't item 2 a duplicate of https://github.com/ImagingDataCommons/IDC-WebApp/issues/490 ? We already discussed that issue, and I thought agreed on something there.

> rather than a history of them

No one brought up history here, so I am not sure if this is related to a different ticket?

**Comment by s-paquette** [comment] 2022-03-17 17:08
@fedorov I think these are possibly duplicate tickets. History wasn't brought up elsewhere, it just occurred to me to double-check on it as a desired item.

Do we want to closer this ticket and go with #490 as the ticket? Or this one?

**Comment by fedorov** [comment] 2022-03-17 21:32
In my view, earlier ticket always takes precedence, but I am fine with any approach you guys choose. I just wanted to make sure discussions and decisions made earlier are not lost.

**Comment by pgundluru** [comment] 2022-05-11 21:13
Last export is now available on test tier and clicking on the link takes me to console with the saved cohort.

**Closed** 2022-05-23 21:45 UTC
Labels: duplicate, enhancement, merged:dev, testing needed, testing passed, cohorts
