### ISSUE TITLE
When dev-portal logs me out, I am brought to idc-dev

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#612] opened 2021-05-05 18:18 UTC
when dev-portal logs me out, I am brought to idc-dev

![image](https://user-images.githubusercontent.com/313942/117189921-bfdf6180-adac-11eb-9de5-f9ce66e08c11.png)

**Comment by s-paquette** [comment] 2021-06-01 19:18
Problem in the .env file's base URL setting, should be fixed on dev and test.

**Comment by madelyngreyes** [comment] 2021-06-09 20:52
I have still been seeing a 400 error.

**Comment by s-paquette** [comment] 2021-06-10 05:55
@madelyngreyes Can you confirm which tier you're getting the 400 on? I can't reproduce this on dev.

**Comment by s-paquette** [comment] 2021-06-10 17:13
@madelyngreyes Can I get a screenshot? (Including the browser bar.) @fedorov Will do, I'll drop it from the Sprint.

**Comment by s-paquette** [comment] 2021-06-18 03:48
@pgundluru @madelyngreyes I can't reproduce this bug anymore, but if you can and could send me a screenshot that would be appreciated. it needs to be tested on each tier individually due to how logouts and redirects function.

**Closed** 2021-06-21 15:46 UTC
Labels: bug, testing needed
