### ISSUE TITLE
explore page pre-login bug on production tier

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#519] opened 2021-01-12 14:04 UTC
Certain filter selections are not saved in the filter definition panel after you login. 

Steps to reproduce below, 

1. open the explore page
2. select the filter lidc_idri from the collections panel 
3. Go to the related tab and select age at diagnosis range e.g., 31-90
4. 24 collections are listed in the collections panel
5. select the login to save cohort button
6. login to the IDC
7. the filter definition panel is empty, no filters are "saved"

<img width="951" alt="after login filter selection not listed" src="https://user-images.githubusercontent.com/16824894/104324153-0c78f700-54b5-11eb-8f21-cfeed6b88d2f.PNG">

**Comment by G-White-ISB** [comment] 2021-02-04 17:53
hmmm. You CAN'T go to explore without logging in on the dev tier (or locally as configured). How is this checked in dev?

**Comment by s-paquette** [comment] 2021-02-04 18:01
This is one that has to be rested in production. Since it's from 21 days ago it should be on prod now.

**Comment by G-White-ISB** [comment] 2021-02-08 19:51
No this test case is still failing in production. Also, pressing the 'sign-in' button should also the preserve filter selections. This never happens

**Comment by fedorov** [comment] 2021-02-09 17:26
I can reproduce this bug in production.

**Comment by madelyngreyes** [comment] 2021-02-09 17:32
I can also reproduce the bug in the production tier.

**Comment by G-White-ISB** [comment] 2021-02-09 20:01
Its fixed in the local environment.
Note expected behavior is that clicking 'login to save' will preserve the filter. However the user will still have to click  'Save As New Cohort' afterwards. 
I am also changing the behavior of the 'Sign In' button so that logging in that way will also preserve the filter.

**Closed** 2021-03-05 17:10 UTC
Labels: bug, explore page, merged:dev, testing needed in production
