### ISSUE TITLE
Improve styling of the collections tab

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#210] opened 2020-08-17 16:58 UTC
Alignment of children under TCGA should be to the right of the parent, and the color for the font should be consistent for all items in the collections panel.

![image](https://user-images.githubusercontent.com/313942/90422778-5934df00-e089-11ea-9e47-f2c835e63518.png)

**Comment by madelyngreyes** [comment] 2020-09-11 14:44
Looks much better! 

But, I believe we should remove the "Show More" from the detailed list of the TCGA collection options we have available.  No additional collections are displayed with the selection of the "Show More" option. 

<img width="219" alt="show more for the collections tab" src="https://user-images.githubusercontent.com/16824894/92939334-a489a580-f41b-11ea-8c29-734c3c68ecd0.PNG">
<img width="221" alt="slow less for the collections tab" src="https://user-images.githubusercontent.com/16824894/92939339-a81d2c80-f41b-11ea-92af-f59d63c6bf58.PNG">

**Comment by mitianisb** [comment] 2020-09-11 16:31
Thanks for the feedback Madelyn! I think this is a bug. I feel it should work like when TCGA is expanded, only a small set of rows (5-6) are shown. And click "show more" will show all the 21 rows, and click "show less" again will show the small set only. If @fedorov can confirm that's what we want, I can work on fix it.

**Comment by fedorov** [comment] 2020-09-11 22:00
Can you move the collections that are children of TCGA to the right to communicate that they are subordinate to the parent? Right now they are lined up with the parent.

![image](https://user-images.githubusercontent.com/313942/92976499-a32a9e00-f458-11ea-9f6f-8b13f894a0d1.png)

**Comment by mitianisb** [comment] 2020-09-13 06:09
Thanks Andrey! I think this was caused by a bad merge. I have fixed it again and will merge into master soon. I also noticed the show more/show less bug has been fixed in the latest.

**Comment by s-paquette** [comment] 2020-09-15 05:50
@fedorov Can you let us know if the current version is improved?

**Comment by fedorov** [comment] 2020-09-15 13:52
Yes, this is resolved as far as I am concerned!

**Closed** 2020-09-15 13:53 UTC
Labels: MVP, enhancement, explore page, merged, testing passed
