### ISSUE TITLE
In Production Environment, Version compare button to compare different data versions of saved cohorts is non functional 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#809] opened 2021-11-24 17:28 UTC
Summary - This is observed in W10 and Mac OS. The version compare button is non functional for saved cohorts from different data versions.

**Comment by pgundluru** [comment] 2021-11-24 20:00
Update - I am able to use the compare version button for some cohorts and not for others. I will reach out to Suzanne to show her my results and validate this issue.

**Comment by s-paquette** [comment] 2021-12-03 18:17
So far we haven't been able to nail down what's causing this. Will have to wait until I can reliably reproduce it in a local environment.

**Comment by s-paquette** [comment] 2021-12-03 18:18
Closing, duplicate of 808.

**Closed by s-paquette** 2021-12-03 18:18 UTC
Labels: bug, triage needed, production
