### ISSUE TITLE
Select all cohorts on the cohorts list page will return the error to contact the administrator 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#624] opened 2021-05-13 21:57 UTC
https://user-images.githubusercontent.com/16824894/118192420-1d5e5880-b414-11eb-8178-eed15c7dbcf0.mov

**Comment by s-paquette** [comment] 2021-05-24 03:12
Closing asa duplicate of #622

**Closed by s-paquette** 2021-05-24 03:12 UTC
Labels: bug, cohorts, priority
