### ISSUE TITLE
Webapp shows studies from cases not in cohort

### ISSUE THREAD

**Issue by bcli4d** [ImagingDataCommons/IDC-WebApp#259] opened 2020-09-08 18:41 UTC
In the webapp, create this filter:
`COLLECTION IN (tcga_read) AND MODALITY IN (Computed Tomography, Digital Radiography) AND TCGA.RACE IN (White)`
Note that in the 'Collections' table it says Total # of Cases is 3 and Total # of Cases(this cohort) is 2. 

Now click on 'tcga_read'. Note that the Selected Studies table displays studies from 3 cases (it might not show all of them until you change Show Entries). I.E. it shows studies from all cases not just from selected cases. 

This is not specific to this filter. I showed this to George who agreed it is a bug.

**Comment by G-White-ISB** [comment] 2020-09-09 17:02
Duplicate of https://github.com/ImagingDataCommons/IDC-WebApp/issues/251

**Closed by G-White-ISB** 2020-09-09 17:02 UTC
