### ISSUE TITLE
Portal footer is no compliant with NCI requirements

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#449] opened 2020-11-21 13:50 UTC
The MVP portal footer is not compliant with HHS/NIH/NCI requirements. For guidance see the footer of PDC and GDC.
![image](https://user-images.githubusercontent.com/3019001/99878893-86d47b80-2bd6-11eb-912c-a84b127306e9.png)

**Comment by fedorov** [comment] 2020-12-10 21:16
[NCI-Digital-Style-Guide_8.pdf](https://github.com/ImagingDataCommons/IDC-WebApp/files/5675648/NCI-Digital-Style-Guide_8.pdf) for the footer requirements.

**Comment by fedorov** [comment] 2020-12-10 21:23
Example how external links are handled on one of the NIH sites: https://www.nih.gov/institutes-nih/nih-office-director/office-communications-public-liaison

![image](https://user-images.githubusercontent.com/313942/101831488-fa95e400-3b03-11eb-965f-8c9a14d393ee.png)

**Comment by ulrikew** [comment] 2020-12-10 21:35
Looks like a good way to solve the problem. 
cancer.gov links to this website when users click on the little arrow symbol next to the link that brings them to the external site.
https://www.cancer.gov/policies/linking
Maybe all that needs to be done is place the icon next to the Discourse and GitBook link and link the icon to https://www.cancer.gov/policies/linking which would remove the need for a pop-up window that the user has to close.

**Comment by mitianisb** [comment] 2020-12-14 07:38
@fedorov @ulrikew @wlongabaugh Thanks for the information above. I have been working on this together with #448 and #458. Here is the latest of the updated site footer and header. Please let me know of any feedback. Thank you!

![IDC_SiteFooter_ExternalLink](https://user-images.githubusercontent.com/58752821/102053239-3fd44300-3d9c-11eb-8e31-4db021b210ed.png)

**Comment by fedorov** [comment] 2020-12-14 16:15
@mitianisb I like all the information you included, but I think the formatting could be refined. I suggest we take the items under "MORE INFORMATION", and put those in a single line, separated by | (the same as in the line next to the last one). Then everything from the text on the right hand side is center-justified, and located under the first line. Then we take the items under "FOLLOW US" and again put those in a single line under. Does this make sense?

**Comment by ulrikew** [comment] 2020-12-14 16:19
@mitianisb Much improved! Please review the NCI Digital Style Guide again. The footer section on page 3 states that the Policies links are required (labeled as 5d). 
What do you think about having a Contact Us section that links to the IDC email and repeats the link to Discourse? Keyvan had suggested/requested to have a link to the email on the home page.

**Comment by mitianisb** [comment] 2020-12-15 00:10
@ulrikew Thanks for the reminders! I have added them in both versions below. In the column version I tried add Contact Us section but it made the columns crowded. So I put them under "More Information" instead.

@fedorov Thanks for suggestion. I thought about it when I started, but worried the current footer text have too many rows will make it look busy. I implemented it now and made both version to compare below.

With columns:
![IDC_Footer_ColumnsVersion](https://user-images.githubusercontent.com/58752821/102151035-c0d81c80-3e26-11eb-9626-6c6172bd35be.png)

With no columns:
![IDC_Footer_NoColumnVersion](https://user-images.githubusercontent.com/58752821/102151039-c2a1e000-3e26-11eb-9939-be8770f6ef96.png)

**Comment by mitianisb** [comment] 2020-12-18 18:18
@fedorov @ulrikew How do you feel about the latest version? which version do we want to proceed? Thanks!

**Comment by fedorov** [comment] 2020-12-18 21:36
My preference is the one with single column.

**Comment by ulrikew** [comment] 2020-12-18 21:52
I don't have a strong preference. Either works for me (until somebody tells us otherwise). 
Andrey, how do you feel about deleting the word consortium from the funding source sentence?

**Comment by fedorov** [comment] 2020-12-20 04:22
Sure, let's remove "consortium".

**Comment by mitianisb** [comment] 2020-12-20 07:06
Ok, I will proceed with the one with a single column and remove 'consortium'. @fedorov Can you let me know which IDC email address I should link to the contact us button? Thanks!

**Comment by fedorov** [comment] 2020-12-21 04:21
support@canceridc.dev

**Comment by fedorov** [comment] 2020-12-21 17:53
> Maybe all that needs to be done is place the icon next to the Discourse and GitBook link and link the icon to https://www.cancer.gov/policies/linking which would remove the need for a pop-up window that the user has to close.

@ulrikew we believe we should have the icon next to the external (non-gov) websites, and when the user clicks those external links, they should be warned by the popup.

**Comment by mitianisb** [comment] 2020-12-22 17:58
@fedorov popup has been added in the dev tier. Please let me know if you have more feedback. Thanks!

**Comment by fedorov** [comment] 2020-12-22 19:45
Looks great, thanks!

**Comment by fedorov** [comment] 2020-12-23 17:27
@mitianisb today when I clicked on Documentation, the page started to open **inside the popup window**. I was not able to reproduce it again. Do you have any idea what might have happened?

**Comment by mitianisb** [comment] 2020-12-24 07:49
@fedorov Good Catch! Fixed and merged in dev tier. Thanks!

**Closed** 2021-01-12 16:28 UTC
Labels: In Progress, merged:dev, testing needed, testing passed
