### ISSUE TITLE
Test Tier - Bladder - OHIF image is not loading and getting Failed to load series

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1137] opened 2023-02-14 15:20 UTC
Test Link:  https://testing-viewer.canceridc.dev/viewer/1.3.46.670589.11.17169.5.0.5244.2015071308371773341 

https://testing-viewer.canceridc.dev/viewer/1.3.46.670589.11.17169.5.0.5244.2015071308371773341?SeriesInstanceUID=1.3.46.670589.11.17169.5.0.2584.2015071308420203679

https://testing-viewer.canceridc.dev/viewer/1.3.46.670589.11.17169.5.0.5244.2015071308371773341?SeriesInstanceUID=1.3.46.670589.11.17169.5.0.2584.2015071308420203679.1

**Steps to reproduce:**

1. Click Bladder from home page under Cases by Major Primary Site list
2. Select Collection Name:PDMR-BL0293-F563 
3. Select Cases: PDMR-BL0293-F563 
4. Select Selected Studies:BL0293-F563-40
5. OHIF images are not loading properly and getting different errors

Error 1:
![image](https://user-images.githubusercontent.com/106698935/218779664-ca0cf8e8-6824-424f-b1c8-c93315e80567.png)

Error 2: 
![image](https://user-images.githubusercontent.com/106698935/218779813-5a092abf-5b41-4ce6-8700-4bb78122954f.png)

Error 3:
![image](https://user-images.githubusercontent.com/106698935/218779927-1a16bdfa-eb77-478e-9fc1-cf4c0cfb864f.png)

[OHIF fail to load series.log](https://github.com/ImagingDataCommons/IDC-WebApp/files/10733902/OHIF.fail.to.load.series.log)

**Comment by VenkatPrema** [comment] 2023-02-14 15:22
Network Response:

.imageViewerViewport.empty~.OHIFCornerstoneViewportOverlay{display:none}.OHIFCornerstoneViewportOverlay{color:#9ccef9}.OHIFCornerstoneViewportOverlay .overlay-element{position:absolute;font-weight:400;text-shadow:1px 1px #000;pointer-events:none}.OHIFCornerstoneViewportOverlay .top-left{top:20px;left:20px}.OHIFCornerstoneViewportOverlay .top-center{top:20px;padding-top:20px;width:100%;text-align:center}.OHIFCornerstoneViewportOverlay .top-right{top:20px;right:20px;text-align:right}.OHIFCornerstoneViewportOverlay .bottom-left{bottom:20px;left:20px}.OHIFCornerstoneViewportOverlay .bottom-left2{bottom:140px;left:20px}.OHIFCornerstoneViewportOverlay .bottom-left3{bottom:160px;left:-20px}.OHIFCornerstoneViewportOverlay .bottom-right{bottom:20px;right:20px;text-align:right}.OHIFCornerstoneViewportOverlay.controlsVisible .bottomright,.OHIFCornerstoneViewportOverlay.controlsVisible .topright{right:39px}.OHIFCornerstoneViewportOverlay .warning{position:absolute;font-weight:400;text-shadow:1px 1px #000;pointer-events:inherit}.OHIFCornerstoneViewportOverlay .warning svg{opacity:1;color:#e29e4a;fill:#e29e4a;stroke:#e29e4a;width:32px;height:28px}.OHIFCornerstoneViewportOverlay svg{color:#9ccef9;fill:#9ccef9;stroke:#9ccef9;background-color:transparent;margin:2px;width:18px;height:18px}#parent-button,#SRlabelcontainer{position:relative}#parent-button.haschild:before{content:"";position:absolute;left:-15px;top:50%;transform:translateY(-50%);width:0;height:0;border-left:7px solid transparent;border-right:7px solid transparent;border-top:9px solid #fff}#child-button{position:absolute;width:100%;max-height:30;overflow:hidden;word-wrap:break-word;white-space:normal;left:20px;transition:height .3s}

**Comment by pieper** [comment] 2023-02-14 16:57
Yes, we should handle this a bit more gracefully, but generally speaking this behavior is what I would expect for a modality we don't (and maybe can't) support.  I believe RawData indicates something very application specific that the viewer is not expected to understand.

We can discuss any changes to improve this behavior of the viewer.

**Comment by s-paquette** [comment] 2023-02-16 20:25
@VenkatPrema @pieper I'd like to ask we close this and the other OHIF tickets, as they should be made in the OHIF repo and not here in the WebApp repo.

**Comment by s-paquette** [comment] 2023-02-16 20:38
Just realized, the real issue is this shouldn't link to opening the viewer. @G-White-ISB This will be another modality to flag with a can't open icon.

**Comment by s-paquette** [comment] 2023-02-16 20:42
Duplicate of #1120

**Closed by s-paquette** 2023-02-16 20:42 UTC
Labels: bug, duplicate
