### ISSUE TITLE
Adjust color schema for pie charts in Search Results panel

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#393] opened 2020-10-14 19:42 UTC
On the dev and the testing tier for Quantitative Analysis in the Search Results panel the color schema doesn't clearly display the slice division between the values present. 

![update color schema](https://user-images.githubusercontent.com/16824894/96037396-c66bb300-0e33-11eb-811f-28c8da2d59e9.PNG)

**Comment by fedorov** [comment] 2020-10-19 16:30
duplicate of #267

**Closed by fedorov** 2020-10-19 16:30 UTC
Labels: bug, explore page
