### ISSUE TITLE
In Test Environment, In the exploration page, when a user selects TCGA collections and selects BMI filter,  The BQ export fails 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#806] opened 2021-11-23 15:29 UTC
In Test environment, In the exploration page, When a user selects TCGA collections as search scope and then clicks on the related filters and selects BMI filter. The BQ export fails to export. 

NOTE - The BQ export is working for other collections and also TCGA when other filters such as age, disease code, modality are selected. 

System - W10 Chrome & Mac Chrome 
Steps to reproduce:
1. In https://testing-portal.canceridc.dev/explore/ 
2. Select TCGA collections in search scope 
3. Select BMI filter (I did a check all)
4. Save cohort and attempt to export to BQ tables 
![image](https://user-images.githubusercontent.com/85526819/143053109-9d693879-016e-4b35-bdb4-94e809f6cf96.png)

**Comment by s-paquette** [comment] 2021-11-23 15:33
@pgundluru this is likely a duplicate of the other BMI ticket; there's a known issue with the BMI None filter that causes exports to BQ to fail. If you could try on a cohort without None as a filter and confirm this, we can close this ticket as a duplicate.

**Comment by s-paquette** [comment] 2021-11-23 15:36
Possible duplicate of #656

**Comment by pgundluru** [comment] 2021-11-23 15:39
Thank You for the prompt response Suzanne, I tried creating a cohort with TCGA collections and only Filter being BMI = NONE and i was able to export the manifest successfully. 

When I select all other options in BMI other than NONE i am seeing a export fail like below 
![image](https://user-images.githubusercontent.com/85526819/143055267-e43c4ce1-ff9c-461d-9647-c06a6d977563.png)

**Comment by s-paquette** [comment] 2021-11-23 15:43
Well that's weird! But since it's the same attribute--let's keep it in the same ticket, since we already have one, 656, to keep it all in one place.

**Closed** 2021-12-03 18:19 UTC
Labels: bug, duplicate, triage needed
