### ISSUE TITLE
Provide invariant linking to per-collection exploration in the webapp

### ISSUE THREAD

**Issue by bcli4d** [ImagingDataCommons/IDC-WebApp#868] opened 2022-01-28 19:21 UTC
We have asked TCIA to include a link on each of its per-collection wiki page to IDC, where such a link would take the user to the web app as if the user had clicked the corresponding collection name on the [IDC Collections page](https://portal.imaging.datacommons.cancer.gov/collections/).
The URL generated by this action is like:
https://portal.imaging.datacommons.cancer.gov/explore/?filters_for_load=%5B%7B%22filters%22:%5B%7B%22id%22:%22120%22,%22values%22:%5B%224d_lung%22%5D%7D%5D%7D%5D
There is concern that the format of these URLs might change over time, and therefore should not be used for this purpose. Instead, IDC should implement some URL format for this purpose that will be invariant.
Note, TCIA has not formally agreed to add such links. So implementation should be deferred until such there is such agreement.

**Comment by s-paquette** [comment] 2022-01-28 20:47
I was thinking about this the other day, and I think what we would do it NOT utilize the filters_for_load call. That one is for us to use on the backend to various ends, and suits our specific formats. We have code that relies on how it works.

Instead we would make a new route, something like explore/filters/?collection=x&collection=y and so on. This doesn't work well for us to use in our own backend API, but we can provide an API for users which is wholly separate that then is put through to the primary API after some translation.

This way, TCIA (or whomever) can always have explore/filter/?x=y&w=z sitting around, and we would handle back-translation into our own system. (This is how PDC does it, and I like this approach as it keeps users away from the messy knowledge of the backend while letting us keep the backend functioning as intended.)

**Comment by fedorov** [comment] 2022-02-03 15:17
Note that ICDC is already linking to IDC collections using current approach: https://caninecommons.cancer.gov/#/study/GLIOMA01.

**Comment by fedorov** [comment] 2022-02-07 18:11
![image](https://user-images.githubusercontent.com/313942/152846894-9ca5849a-4af9-437b-b477-201b910a542c.png)

**Comment by s-paquette** [comment] 2022-02-07 20:08
Proposed format:

`https://portal.imagingdatacommons.cancer.gov/explore/filters/?collection_id=x`

for multiple attributes or attributes with multiple values:

`https://portal.imagingdatacommons.cancer.gov/explore/filters/?collection_id=x&collection_id=y&BodyPartExamined=z`

**Comment by fedorov** [comment] 2022-02-07 20:50
> Proposed format: `https://portal.imagingdatacommons.cancer.gov/explore/filters/?collection_id=x`

@s-paquette what is the format of `x` in the example above that you had in mind?

**Comment by s-paquette** [comment] 2022-02-07 21:07
x would be the value in our Solr cores/BQ pivot. So, for collection_id, that's one we manage ourselves, eg:

`https://portal.imagingdatacommons.cancer.gov/explore/filters/?collection_id=4d_lung&collection_id=tcga_brca`

BodyPartExamined is trickier; it has spaces and non-URL compliant values. For that one, users need to URI encode the URL:

`https://portal.imagingdatacommons.cancer.gov/explore/filters/?BodyPartExamined=ABD%20PELV`

**Comment by s-paquette** [comment] 2022-02-07 21:13
Prototype seems to be working well, I'll see if I can get it onto dev later today:
![image](https://user-images.githubusercontent.com/8442808/152872833-ae0f1134-e565-44a1-a39e-1dbadf6d6e98.png)

**Comment by fedorov** [comment] 2022-02-07 22:12
This is a duplicate of #730

**Comment by fedorov** [comment] 2022-04-07 18:07
Remaining part that needs to be done is instructions for TCIA on how they should form the links for the collections pages. Let's keep this open until this is resolved. I will take care of this.

**Closed** 2022-04-14 17:37 UTC
Labels: enhancement, merged:dev, testing needed, testing passed, priority, In Progress
