### ISSUE TITLE
certain filter selection options will return an error when using the BQ export functionality

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#541] opened 2021-02-01 16:52 UTC
**General description**

While testing another ticket the filter selection, Modality:Computed Tomography Digital Radiography Object Class:CR Image PET Image Primary Site Location:Bladder will return an, "Unable to export cohort file manifest to table canceridc-user-data.user_manifests.manifest_cohort_108_20210201_164912--please contact the administrator." error message. 

**Steps to reproduce the behavior**

1.  go to the exploration page 
2. select filter options, Modality:Computed Tomography Digital Radiography Object Class:CR ImagePET Image Primary Site Location:Bladder
3. save cohort
4. select the export cohort manifest BigQuery option
5. returned the error message, "Unable to export cohort file manifest to table canceridc-user-data.user_manifests.manifest_cohort_108_20210201_164912--please contact the administrator."

**Screenshots**
![cohort filter selection is returning errors on the production tier](https://user-images.githubusercontent.com/16824894/106490490-df9c7c00-6483-11eb-8262-06b7a11b3957.PNG)

**Your System**
 - OS: Windows
 - Browser: Chrome
 - Version: canceridc.202101111506.0a8af57

**Comment by G-White-ISB** [comment] 2021-02-01 16:58
I get the same thing
OS:Mac
Browser: Chrome

**Comment by G-White-ISB** [comment] 2021-05-17 21:07
Cannot seem to export cohorts on either dev or testing portals right now.

**Comment by s-paquette** [comment] 2021-05-17 22:51
@G-White-ISB Can you specify what filters are a problem? I can export just fine at the moment, but it might be related to the specific filters I have.

**Comment by s-paquette** [comment] 2021-05-17 22:53
Note, I'm unable to reproduce this error on dev.

**Comment by G-White-ISB** [comment] 2021-05-17 23:08
I have one cohort with collection in TCGA* and modality in Magnetic Resonance, and another with collection in ISPY1(ACRIN 6657). Neither csv download or BQ exports were successful

<img width="1133" alt="Screen Shot 2021-05-17 at 4 01 54 PM" src="https://user-images.githubusercontent.com/58443591/118566806-6b7f9e80-b729-11eb-98ad-9ebb45d1600b.png">
<img width="1133" alt="Screen Shot 2021-05-17 at 4 01 54 PM" src="https://user-images.githubusercontent.com/58443591/118566872-89e59a00-b729-11eb-99ad-6614a21208cc.png">
<img width="1126" alt="Screen Shot 2021-05-17 at 4 01 06 PM" src="https://user-images.githubusercontent.com/58443591/118566917-ab468600-b729-11eb-879f-21f79c651f03.png">

**Comment by s-paquette** [comment] 2021-05-17 23:14
got it--will test with those.

**Comment by s-paquette** [comment] 2021-05-17 23:21
@G-White-ISB One issue is 'hide zeroes' is being sent as a filter during saves:

selected-filters: {"1":["TCGA"],"107":["MR"],"120":["tcga_blca","tcga_brca","tcga_cesc","tcga_coad","tcga_esca","tcga_gbm","tcga_hnsc","tcga_kich","tcga_kirc","tcga_kirp","tcga_lgg","tcga_lihc","tcga_luad","tcga_lusc","tcga_ov","tcga_prad","tcga_read","tcga_sarc","tcga_stad","tcga_thca","tcga_ucec"],"undefined":["hide-zeros"]}

**Comment by G-White-ISB** [comment] 2021-05-20 16:53
Several things: 
1. If one selects 'hide zeros' in the Collections tab then "undefined":["hide-zeros"] gets sent as filter and the cohort is not saved. Thats clearly a front end issue.
2. I am now consistently exporting cohorts successfully via BQ in local environment. On dev tier xxport via BQ is RANDOMLY SUCCESSFUL, even with identical cohort. I don't have insight here. 
3. I see a new specific bug in exporting to file in local environment even with tiny cohorts (43 cases)
   Traceback (most recent call last):
  File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 509, in get_collex_metadata
    search_child_records_by=search_child_records_by)
  File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 613, in get_metadata_solr
    if attr_name in all_ui_attrs['sources'][source.id]['list']:
KeyError: 11

Not sure if we need to create separate tickets for these bugs or just squash them

**Comment by s-paquette** [comment] 2021-05-20 17:01
I suspect #3 is related to an extent ticket. #2 I'll look into, make a ticket if needed. #1 if you can fix it quickly, no need for a ticket, just go ahead and PR when it's ready to go. If it looks like it'll be more work, then make a ticket I think, just to track your time for reporting etc.

**Comment by s-paquette** [comment] 2021-06-10 20:15
@G-White-ISB Ah ha, #3 is from the ticket about random 500s. That one I have in fact fixed, or I'm about certain I have. I expect this ticket is a convolution of several others: #641 #642 #617 . If you've already fixed item #1, I think we can close this as a duplication of all of those tickets.

**Comment by s-paquette** [comment] 2021-06-18 03:50
Closing as a duplicate of extent issues,

**Closed by s-paquette** 2021-06-18 03:50 UTC
Labels: bug, cohorts, duplicate
