### ISSUE TITLE
[v2] Study/SeriesDescription incorrectly shown as "undefined"

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#611] opened 2021-05-05 16:19 UTC
Example filter:

![image](https://user-images.githubusercontent.com/313942/117174545-d29d6a80-ad9b-11eb-8478-6a4122d0ee93.png)

Selecting study/series shows "undefined" for descriptions:

![image](https://user-images.githubusercontent.com/313942/117174510-c7e2d580-ad9b-11eb-931e-a6ef8d041616.png)

Opening a study in the viewer can be used to confirm that descriptions of series are not "undefined" (SeriesDescription is shown under each of the thumbnails on the left side):

![image](https://user-images.githubusercontent.com/313942/117174721-05dff980-ad9c-11eb-9ee6-3a61f8450dd6.png)

This appears to be a regression from production release.

**Comment by s-paquette** [comment] 2021-05-12 06:25
Partially done: the most recent v2 Solr cores will now properly supply all Series and Study description values available as a list. @G-White-ISB You'll need to concatenate them for display in some manner. For empty values we should leave it blank for now.

**Comment by G-White-ISB** [comment] 2021-05-13 17:47
@fedorov, how should we display study description in cases where there are  multiple descriptions

**Comment by fedorov** [comment] 2021-05-13 21:15
Here are two ideas:
1. pick any one SeriesDescription, show it with an asterisk, and show full list with the descriptions separated by comma in the tooltip
2. show concatenated list of descriptions separated by comma

Probably option 2 is least controversial. What do you think?

**Comment by G-White-ISB** [comment] 2021-06-10 15:53
The current issue is now a duplicate of https://github.com/ImagingDataCommons/IDC-WebApp/issues/638

**Comment by fedorov** [comment] 2021-06-11 03:50
@G-White-ISB how is this a duplicate? The other issue is about long series description name. I don't understand, sorry.

**Comment by G-White-ISB** [comment] 2021-06-11 15:10
@madelyngreyes is reporting a long series description. It is because an array of series descriptions is being displayed. Per our last few comments that is  current subject of this ticket.

**Comment by fedorov** [comment] 2021-06-12 20:38
I guess I was confused, since on this issue there was no follow up on https://github.com/ImagingDataCommons/IDC-WebApp/issues/611#issuecomment-840839409 about what was the decision handling varying SeriesDescription values within a series. I did not realize that decision was already made and implemented. Sounds like that approach of concatenating unique values should be revisited. Should we instead show one of the SeriesDescription values, and the rest in a tooltip?

**Comment by G-White-ISB** [comment] 2021-06-15 17:44
No decisions were made about how to display the multiple descriptions. The descriptions are being sent from the back as a list per @s-paquette's comment, and the current behavior is to show them all. 
I'll try the tooltip approach.

**Comment by s-paquette** [comment] 2021-07-22 17:45
@G-White-ISB I dropped the merged label because this is still happening on dev. Feel free to move this out of Release 22 if you think it won't make it,

**Comment by pgundluru** [comment] 2021-08-18 21:25
![image](https://user-images.githubusercontent.com/85526819/129974390-904c9a3c-85e7-4ff0-8790-8f570a36d2d7.png)

**Closed** 2021-09-17 01:53 UTC
Labels: bug, merged:dev, testing needed, testing passed, In Progress
