### ISSUE TITLE
Feature request - Remove TSV/CSV/JSON AND BQ for import manifest for older versions in IDC portal 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1171] opened 2023-04-27 18:17 UTC
This was requested by Andrey - To completely remove/disable access to select the CSV/TSV/JSON and BQ tabs for older versions of cohorts where it is  currently greyed out.

**Comment by pgundluru** [comment] 2023-04-27 18:18
![image](https://user-images.githubusercontent.com/85526819/234955847-47893532-cb65-4ab4-9378-ae546ab7a3e4.png)

**Comment by s-paquette** [comment] 2023-05-04 16:50
@fedorov Is this not a duplicate of #1178?

**Closed** 2023-11-13 20:18 UTC
Labels: enhancement
