### ISSUE TITLE
Add search capabilities to all search criteria that have more than 25 items

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#450] opened 2020-11-21 13:54 UTC
TCIA currently hosts >100 collections with more than 70 anatomical sites. The user should be able to search within those lists and sort them either alphabetically or numerically.

![image](https://user-images.githubusercontent.com/3019001/99878976-2560dc80-2bd7-11eb-93dc-205bac48d3f9.png)

**Comment by fedorov** [comment] 2020-12-07 15:47
duplicate of #81

**Closed by fedorov** 2020-12-07 15:47 UTC
Labels: duplicate, enhancement, explore page
