### ISSUE TITLE
Data portal at 125% zoom on laptop will cause text overlap and cut-off

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#157] opened 2020-07-09 22:26 UTC
On the data portal, if the user is on a laptop using Google Chrome at 125% zoom, there is text cut-off in the Search Scope panel. As well in the Search Configuration panel, the tab ORIGINAL is cut off. 

development tier
![Screen Shot 2020-07-09 at 6 05 12 PM](https://user-images.githubusercontent.com/16824894/87096752-8207c000-c211-11ea-9484-c22a5bbe58d0.png)

**Comment by s-paquette** [comment] 2020-07-21 18:31
I want to note that this isn't a bug, since that's just how zooming works.

Unfortunately, zooming is very hard to account for, because there's not (currently) a way to tell how zoomed in a browser is or isn't, so you can't adjust your CSS based on zoom level. You can only work with the listed available pixels, and if those are off due to zoom, that's not something you can adjust for.

**Comment by fedorov** [comment] 2020-08-03 16:36
@s-paquette will look further if there are any new approaches to detect zoom at the browser level

**Comment by madelyngreyes** [comment] 2020-08-31 15:55
Mouse over feature will display border box cut off for certain users related to comment, https://github.com/ImagingDataCommons/IDC-WebApp/issues/224#issuecomment-682168215

**Comment by fedorov** [comment] 2021-06-22 03:12
Have you explored these?
* https://www.tutorialexample.com/javascript-detect-web-page-zoom-level-in-browsers-javascript-examples/
* https://www.geeksforgeeks.org/how-to-detect-page-zoom-level-in-all-modern-browsers-using-javascript/

**Comment by s-paquette** [comment] 2022-10-27 22:05
@fedorov Can we close this ticket? I've tried reproducing it but remained unable to. At 125% in Firefox and Chome on Windows 10 I can't reproduce this issue.

**Comment by s-paquette** [comment] 2023-11-13 20:29
Cannot reproduce; we can re-open or resubmit if it comes up again.

**Closed** 2023-11-13 20:28 UTC
Labels: design issue, post-MVP, explore page
