### ISSUE TITLE
In Production Tier, On the Home page, When a user selects SM viewer, The Slide label is blank 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#796] opened 2021-11-11 16:19 UTC
The slide label for SM viewer shows up blank as shown in the image below 
Able to reproduce this one 
Mac - Chrome browser 
W10 - Chrome and Edge 

![image](https://user-images.githubusercontent.com/85526819/141331941-56dc9c97-6214-47ca-894f-4d2e8c754bf7.png)

**Comment by fedorov** [comment] 2021-11-11 16:28
@hackermd @Punzo can you take a look at this?

**Comment by Punzo** [comment] 2021-11-15 08:19
Hi @fedorov @pgundluru I just tried to reproduce, but everything seems working fine a part an initial 404 response:

![image](https://user-images.githubusercontent.com/7985338/141746382-c464107c-0ec4-4ca3-bf8b-d4ba9c6237db.png)

**Comment by fedorov** [comment] 2021-11-16 20:29
Interesting. I had a separate email communication with @hackermd, where he seemed to have acknowledged this issue, and in reference to it said "I identified the problem for that one and am working on fixing it." Unless I misunderstood...

**Comment by Punzo** [comment] 2021-11-17 08:13
uhm no I think the other issue was related to rendering THUMBNAIL that were not divisible for 4 (OpenLayer assuming that color images have always 4 channels): 

![image](https://user-images.githubusercontent.com/7985338/142160985-f78fa384-dca7-4924-80c1-6595ac5a0dac.png)

**Comment by Punzo** [comment] 2021-11-17 08:16
P.S.: I can randonly reproduce the errors, but they looks like they are because of the 404 error. We could try to check these and report warnings.

**Comment by hackermd** [comment] 2021-11-17 15:13
The issue I am aware of is that if the "Slide Label" side bar menu is toggled, the label image can disappear. That problem seems to be related to the sizing of the canvas in the viewport.

There are, however, also slides for which no label images are available.

This particular slide doesn't seem to contain a LABEL image:

```
$ dicomweb_client --url https://proxy.imaging.datacommons.cancer.gov/v1/projects/canceridc-data/locations/us/datasets/idc/dicomStores/v4/dicomWeb retrieve series --study 1.3.6.1.4.1.5962.99.1.2463087261.2121647220.1625960757917.3.0 --series 1.3.6.1.4.1.5962.99.1.2463087261.2121647220.1625960757917.2.0 metadata --dicomize | grep -e 'Image Type'
(0008, 0008) Image Type                          CS: ['DERIVED', 'PRIMARY', 'THUMBNAIL', 'RESAMPLED']
(0008, 0008) Image Type                          CS: ['DERIVED', 'PRIMARY', 'VOLUME', 'RESAMPLED']
(0008, 0008) Image Type                          CS: ['DERIVED', 'PRIMARY', 'VOLUME', 'RESAMPLED']
(0008, 0008) Image Type                          CS: ['DERIVED', 'PRIMARY', 'OVERVIEW', 'NONE']
(0008, 0008) Image Type                          CS: ['DERIVED', 'PRIMARY', 'VOLUME', 'NONE']
```

**Comment by pgundluru** [comment] 2021-11-17 15:20
The issue I noticed and reported in this ticket is related to Marcus comment above "The issue I am aware of is that if the "Slide Label" side bar menu is toggled, the label image can disappear. That problem seems to be related to the sizing of the canvas in the viewport."

Thank you @Punzo and @hackermd  for looking into this issue. Please let me know how I can help.

**Comment by hackermd** [comment] 2021-11-17 15:29
@pgundluru could you share links to affected slides (i.e., slides that have a LABEL image) or share the corresponding Study, Series, and Instance UID?

**Comment by fedorov** [comment] 2021-11-18 14:29
> could you share links to affected slides (i.e., slides that have a LABEL image) or share the corresponding Study, Series, and Instance UID?

@pgundluru we discussed this with @hackermd today. Once Markus provides the details on how the images with the LABEL image can be identified using DICOM metadata, I will follow up and try to address this.

**Comment by hackermd** [comment] 2021-11-18 18:54
@fedorov the images can be identified based on their [Image Type](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.12.4.html#sect_C.8.12.4.1.1): `image.ImageType[2] == "LABEL"` .

**Comment by fedorov** [comment] 2021-11-19 16:23
@hackermd for the current IDC data version, I do not see any SM instances that have `LABEL` in `ImageType`.

```sql
SELECT
  DISTINCT(ARRAY_TO_STRING(ImageType,","))
FROM
  `canceridc-data.idc_current.dicom_all`
WHERE
  Modality = "SM"
```

Result:

![image](https://user-images.githubusercontent.com/313942/142656630-3fd5c360-4cc5-4aa8-a200-09810d960b1f.png)

**Comment by hackermd** [comment] 2021-11-19 18:23
> @hackermd for the current IDC data version, I do not see any SM instances that have LABEL in ImageType.

Hmm...will need to look into it. @dclunie did we omit them upon conversion or import into the DICOM store?

**Comment by dclunie** [comment] 2021-11-19 21:59
That's correct, no LABEL images are produced by my SVS to DICOM converter.

**Comment by hackermd** [comment] 2021-11-19 22:06
@fedorov @pgundluru that explains why we don't see any label images :)

There is an issue with display of label images when toggling the "Label image" menu in the viewer. Will be fixed with the next release.

**Closed by hackermd** 2021-11-19 22:06 UTC
Labels: bug, triage needed, production

**Comment by fedorov** [comment] 2021-11-19 22:13
@hackermd makes sense! Is that runtime error in the console related and expected, or will also be fixed in the next release?

**Comment by hackermd** [comment] 2021-11-19 22:44
I think that problem occurs [here](https://github.com/MGHComputationalPathology/slim/blob/ad879b2c9cc90bbce602a6feeca72e189f015cfe/src/components/SlideViewer.tsx#L374) and seems to be an issue with the implementation of the DICOMweb Search Transaction in the proxy. The proxy currently returns an empty payload instead of an empty JSON array when a query doesn't match any resources. The behavior should be changed for handling response messages with 204 status codes.

**Comment by hackermd** [comment] 2021-11-19 22:45
@pieper do you think my assessment is correct?

**Comment by fedorov** [comment] 2021-11-19 22:52
Since the proxy was mentioned, looping in @wlongabaugh.

**Comment by wlongabaugh** [comment] 2021-11-19 23:02
I seem to recall something like this a few months ago, where the issue was that Google Cloud Healthcare DICOMWeb was returning 404s instead of an empty dictionary? Note that the proxy does absolutely no interpretation of the DICOM traffic, so I suspect it is upstream.

**Comment by fedorov** [comment] 2021-11-19 23:10
> I think that problem occurs [here](https://github.com/MGHComputationalPathology/slim/blob/ad879b2c9cc90bbce602a6feeca72e189f015cfe/src/components/SlideViewer.tsx#L374) and seems to be an issue with the implementation of the DICOMweb Search Transaction in the proxy.

@hackermd is the link accurate? I don't code in JS, and I am afraid I don't know enough about DICOMweb, but it seems to refer to a section of the code that handles annotations.

**Comment by hackermd** [comment] 2021-11-20 14:23
It happens when the viewer searches for SR documents. When none are found, the server is expected to respond with 204 status code and include payload containing an empty JSON array. Currently, the server responds with 200 status and includes an empty payload, resulting in a JavaScript `null`, which doesn't have a `forEach` method.

We can work around this in the viewer, but this should really be fixed server-side. If the Healthcare API is to blame, we may want to fix it in the proxy.

**Comment by pieper** [comment] 2021-11-20 14:24
Have you tested google's dicomweb without the proxy?

**Comment by hackermd** [comment] 2021-11-20 17:51
> Have you tested google's dicomweb without the proxy?

It seems to be an issue with the Healthcare API

**Comment by hackermd** [comment] 2021-11-20 18:05
I just realized that I reported the issue to Google several months ago...Will meanwhile provide a patch in Slim.

**Comment by hackermd** [comment] 2021-11-21 21:59
https://github.com/MGHComputationalPathology/slim/releases/tag/v0.4.4
