### ISSUE TITLE
selection of sapien cases count doesn't match the exploration page cases count for selection

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#625] opened 2021-05-13 23:31 UTC
From the homepage the selection of the sapien filter option e.g. skin has a cases count of 141 cases. After this option is selected on the homepage the body part examined skin 60 cases are present for the filter. 

The same can be seen for other filter selection options. 

https://user-images.githubusercontent.com/16824894/118199727-b3e54680-b421-11eb-8d4a-65cde8afa223.mov

**Comment by madelyngreyes** [comment] 2021-05-21 16:48
Similar issue can be seen with the selection of a bar chart value. The count on the homepage doesn't match the count on the exploration page for the number of cases for the filter selection.

**Comment by s-paquette** [comment] 2021-05-24 03:32
The counts on the homepage are from the collections table itself, so it's possible the numbers there need looking at. I'll double-check and then ping BillC about it.

**Comment by s-paquette** [comment] 2021-05-25 16:31
This is likely related to #635.

**Comment by s-paquette** [comment] 2021-06-09 06:57
So it turns out this is some kind of issue in the dicom_all view. 

```
SELECT DISTINCT collection_id, COUNT(*)
FROM (
SELECT DISTINCT PatientID, collection_id FROM `idc-dev-etl.idc_v2.dicom_all` WHERE tcia_tumorLocation='Skin')
GROUP BY collection_id
;
```
This gives me:
```
cptac_cm            13
anti_pd_1_melanoma  47
```

But in the collections metadata table:
```
SELECT idc_webapp_collection_id, Subjects 
FROM `idc-dev-etl.idc_v2.original_collections_metadata`
WHERE Location='Skin';
```
```
anti_pd_1_melanoma  47
cptac_cm            94
```

@bcli4d Not clear what the issue is but it seems cptac_cm has some numbers issues.

**Comment by bcli4d** [comment] 2021-06-09 15:43
This appears to be an error in the [TCIA Data Collections table.](https://www.cancerimagingarchive.net/collections/) which says there are 94 subjects in CPTAC-CM. However, the [TCIA CPTAC-CM wiki detailed descriptions page ](https://wiki.cancerimagingarchive.net/display/Public/CPTAC-CM#33948224171ba531fc374829b21d3647e95f532c) shows 13 'participants' which is the number of distinct patient_IDs in dicom_all.

Actually, if my SQL:
```
with cases_per_collection as (SELECT DISTINCT collection_id, COUNT(*) as cases
FROM (
SELECT DISTINCT PatientID, collection_id FROM `idc-dev-etl.idc_v2.dicom_all`)
GROUP BY collection_id)
select cpc.*, o.Subjects  
from cases_per_collection as cpc
join `idc-dev-etl.idc_v2.original_collections_metadata` as o
on cpc.collection_id = o.idc_webapp_collection_id 
where cpc.cases != o.Subjects 
order by cpc.collection_id 
```
 is correct, there are 16 collections where this is the case (no pun intended):

Row | collection_id | cases | Subjects | &nbsp;
-- | -- | -- | -- | --
1 | cptac_ccrcc | 63 | 222 | &nbsp;
2 | cptac_cm | 13 | 94 | &nbsp;
3 | cptac_gbm | 66 | 189 | &nbsp;
4 | cptac_hnscc | 64 | 112 | &nbsp;
5 | cptac_lscc | 37 | 212 | &nbsp;
6 | cptac_luad | 33 | 244 | &nbsp;
7 | cptac_pda | 98 | 168 | &nbsp;
8 | cptac_sar | 24 | 94 | &nbsp;
9 | cptac_ucec | 74 | 250 | &nbsp;
10 | icdc_glioma | 57 | 78 | &nbsp;
11 | lung_pet_ct_dx | 355 | 363 | &nbsp;
12 | pancreas_ct | 80 | 82 | &nbsp;
13 | pseudo_phi_dicom_data | 42 | 21 | &nbsp;
14 | qin_breast | 68 | 67 | &nbsp;
15 | qin_headneck | 156 | 279 | &nbsp;
16 | rider_lung_pet_ct | 243 | 244 | &nbsp;

**Comment by bcli4d** [comment] 2021-06-09 16:23
Of course, it could be that I have not somehow downloaded all data and/or that some of the differences are due to TCIA having added to a collection since I did the download. However, in the case of cptac-cm at least, our numbers match the wiki numbers. 
[This](https://wiki.cancerimagingarchive.net/display/Public/CPTAC+Imaging+Proteomics) page shows that the Subjects numbers on the TCIA data collections page for CPTAC collections correspond to "Pathology Total" counts.

**Comment by bcli4d** [comment] 2021-06-10 01:21
I compared  our case counts above  (the cases column) with counts shown on the TCIA radiology exploration page. Our counts match those shown on the page except for qin_headneck, which has had 123 cases added since we downloaded it last Fall.

**Comment by s-paquette** [comment] 2021-06-10 06:45
Going to move this into Sprint 22 since this is an issue that goes further than just a mixup of some sort.

**Comment by s-paquette** [comment] 2021-06-10 06:46
@fedorov @wlongabaugh @bcli4d What do we need to do to address this/can we address this?

**Comment by fedorov** [comment] 2021-06-10 14:21
Is sapiens populated from the collection-level metadata, as opposed to the counts from the dicom_all table?

I think this argues for NOT using the case counts from the collections table, and instead counting distinct PatientIDs in dicom_all. I should report this to TCIA, but I don't hold my breath to see this resolved anytime soon. The right way to resolve it is to have everything in the collection-level table available via API, and if I recall it correctly, it's part of TCIA/PRISM "collection manager", which is year(s?) away.

**Comment by bcli4d** [comment] 2021-06-10 20:00
@fedorov do you want the Subjects column in the original_collections_ metadata table populated from our data?

**Comment by fedorov** [comment] 2021-06-11 03:35
@bcli4d yes, I believe this is the right approach, since we want sapiens to show counts corresponding to the data we have in IDC.

**Comment by bcli4d** [comment] 2022-03-16 21:41
original_collections_metadata Subjects values are the number of subjects in IDC data.
This can be closed.

**Comment by bcli4d** [comment] 2022-08-16 23:49
@fedorov, @s-paquette  Can we close this?

**Closed** 2023-11-13 20:44 UTC
Labels: bug, home page, explore page, further discussion needed
