### ISSUE TITLE
manifest export fix default file download selection from cohort list test tier

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#516] opened 2021-01-08 17:34 UTC
Selecting a previously created cohort, then from the cohort details select the export cohort manifest button. The files download option is available when it should be disabled.  Issue is found only on the test tier. 

Steps to reproduce the issue,

1. create large cohort e.g. all collections
2. go to previously created cohort list table 
3. select large cohort 
4. open the export cohort manifest button 
5. the file download option is the default export option

![2021-01-08](https://user-images.githubusercontent.com/16824894/104046201-b56ddc00-51ad-11eb-88db-9b0d16a12457.png)

**Comment by mitianisb** [comment] 2021-01-10 06:50
@madelyngreyes I have tried it on the test tier and got this to happen only sometimes (2 out of 7 tries for All_Collections). The cause is an ajax call in image_search.js returned failure from the backend. See screenshot below. Because of the failure the code to disable the filters on the left, and the code to show the "max size" warning and disable files download is never run. So they don't work correctly.

@s-paquette I tried many times but do not repro the same problem in dev tier. Maybe some setting difference between test and dev tier make test tier fail sometimes?

![image](https://user-images.githubusercontent.com/58752821/104116381-ded15980-52cc-11eb-8a8c-d660f71441c2.png)

**Comment by s-paquette** [comment] 2021-01-11 17:44
@mitianisb @madelyngreyes This is related to a backend bug, and not related to this ticket. I'll make a new one for what you're encountering here, which seems to be related to derived data. If you could make a non-derived data cohort to test for now, you can resume testing this specific bug (which is not related to this error).

**Comment by s-paquette** [comment] 2021-01-11 17:46
@mitianisb @madelyngreyes Sorry, I thought this was a different ticket! So I retract that bit about making a new one. Any time you see an error in the console followed by 'problem getting data' this means there was an error on the backend, rather than the front end, and you want to hit the AppEngine logs to dig it up. (You can also see the 500 return line just above it.) 

I've been tracking this one and am still trying to sort it out, as you've both noted it's intermittent but I think it's derived data related.

**Comment by G-White-ISB** [comment] 2021-05-17 21:00
Still an issue

**Comment by s-paquette** [comment] 2021-05-17 22:50
@G-White-ISB Can you specify what kind of error you're getting, or what's happening, and what filters you used? I can't reproduce this with any of my current cohorts on dev.

**Comment by s-paquette** [comment] 2021-06-08 19:57
@G-White-ISB Can you update me on this one?

**Comment by s-paquette** [comment] 2021-06-18 03:56
I'm going to go ahead and close this one for now, since no one's been able to update me on it, and we've significantly restructured the backend with the v2 data. We can open a new ticket if needed.

**Closed by s-paquette** 2021-06-18 03:56 UTC
Labels: bug, cohorts
