### ISSUE TITLE
In production, Cohort export to BQ fails for TCGA collections and any related filters with no console errors 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#838] opened 2022-01-12 22:52 UTC
Summary: Cohort export to BQ fails for TCGA collections. When  a user selects TCGA collections and any related filters, Then tries to export the saved cohort manifest to BQ, There is an error "There was an error exporting your cohort to BigQuery. Please contact the administrator."

System - W10, chrome

Steps to reproduce:

1. In exploration page, select TCGA collections and select any filter (eg. age at diagnosis or disease code)
2. Save the cohort and go to the cohort page 
3. click on export manifest and get BQ 
4. The export fails

**Comment by pgundluru** [comment] 2022-01-12 23:23
I am able to export to BQ if i select TCGA collections and any original filter so this seems to be limited to TCGA with related filters

**Comment by s-paquette** [comment] 2022-01-21 19:07
Closing, this is a duplicate of other tickets.

**Closed by s-paquette** 2022-01-21 19:07 UTC
Labels: bug, duplicate, production
