### ISSUE TITLE
Inconsistency in use of upper and lower case collection names

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#491] opened 2020-12-14 19:12 UTC
The collection names are capitalized in the left-side search menu and in lower case as part of the crumb trail. 
![image](https://user-images.githubusercontent.com/3019001/102124425-3edff780-3e16-11eb-89b7-3ad04a0a938d.png)

**Comment by fedorov** [comment] 2020-12-14 20:38
Duplicate of https://github.com/ImagingDataCommons/IDC-WebApp/issues/414

**Closed by fedorov** 2020-12-14 20:38 UTC
Labels: duplicate, triage needed
