### ISSUE TITLE
On the cohort page, Include a notice in the filter definition panel when the defined filter includes limit access data 

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#885] opened 2022-02-10 19:11 UTC
If the defined filter includes limit access collections a text box in the filter definition panel will state 'Note: the defined filter includes cases belonging to limited access collections'.

**Comment by fedorov** [comment] 2022-02-10 19:14
duplicate of #836

**Comment by fedorov** [comment] 2022-02-10 19:15
This is triggered by https://discourse.canceridc.dev/t/user-does-not-have-storage-objects-list-access-to-the-google-cloud-storage-bucket/249/3

**Comment by pgundluru** [comment] 2022-03-21 14:05
"This cohort includes collections with limited access. The DICOM files of these collections are not publicly available" is now available for limited access data

**Closed** 2022-04-08 17:08 UTC
Labels: enhancement, merged:dev, testing needed, testing passed, priority
